[rethink]
debug = false
host = "localhost"

[irc]
enable = true
debug = false
host = "chat.freenode.net"
port = 6667
tls = false
nick = "msks"
username = "msks"
password = ""
gecos = "Mr. Meeseeks"
channels = ["#meeseekeria"]
silentChannels = []
admins = ["daGrevis"]

[http]
clientPath = "../client/build"
# clientPath = { msks = "/srv/msks", developerslv = "/srv/developerslv" }
