version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    links:
     - rethink
     - msks
    ports:
     - '80:80'
    volumes:
     - ~/msks/nginx.conf:/etc/nginx/nginx.conf:ro
     - ~/msks/build:/srv/msks:ro
    restart: always

  rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
     - ~/msks/rethink-data:/data
    restart: always

  msks:
    container_name: msks
    image: msks
    links:
     - rethink
    ports:
     - '3001:3001'
    volumes:
     - ~/msks/config.toml:/usr/src/app/config.toml:ro
     - ~/msks/build:/srv/msks:ro
    restart: always
