version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    links:
     - rethink
     - msks
    ports:
     - '80:80'
    volumes:
     - ~/msks/nginx.conf:/etc/nginx/nginx.conf:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    restart: always

  rethink:
    container_name: rethink
    image: rethinkdb
    volumes:
     - ~/msks/rethink-data:/data
    restart: always

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
     - ~/msks/elastic-data:/usr/share/elasticsearch/data
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - bootstrap.memory_lock=true
     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

  msks:
    container_name: msks
    image: msks
    links:
     - rethink
     - elastic
    volumes:
     - ~/msks/config.toml:/usr/src/app/config.toml:ro
     - ~/msks/build:/srv/msks:ro
     - ~/msks/developerslv:/srv/developerslv:ro
    restart: always
