version: '3'

services:
  elastic:
    image: 'elasticsearch:6.6.0'
    ports:
     - '9200:9200'
    environment:
     - bootstrap.memory_lock=true
     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
     - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
  postgres:
    build: 'src/postgres'
    ports:
     - '5432:5432'
    links:
     - 'elastic:elastic'
